(define operation-table (make-table))
(define get (operation-table 'lookup-proc))
(define put (operation-table 'insert-proc))

(define (install-sum-package)
	(define (addend s)
		(car s))
	(define (augend s)
		(cadr s))
	(define (make-sum x y)
		(cond ((=number? x 0)
			y)
			((=number? y 0)
				x)
			((and (number? x) (number? y))
				(+ x y))
			(else
				(attach-tag '+ x y))))
	(put 'addend '+ addend)
	(put 'augend '+ augend)
	(put 'make-sum '+ make-sum)
	(put 'deriv '+ 
		(lambda (exp var)
			(make-sum (deriv (addend exp) var)
					  (deriv (augend exp) var))))
	'done)
	
(define (make-sum x y)
	((get 'make-sum '+) x y))
	
(define (addend sum)
	((get 'addend '+) (contents sum)))
	
(define (augend sum)
	((get 'augend '+) (contents sum)))