(define (make-account balance password)
  (let ((password-failures 0))
    (define (withdraw amount)
	  (set! password-failures 0)
	   (if (>= balance amount)
	    (begin (set! balance (- balance amount))
		 balance)
		"insufficient funds"))
    (define (deposit amount)
	 (set! password-failures 0)
	 (set! balance (+ balance amount))
	  balance)
	(define (block-access amount)
	 (set! password-failures (+ 1 password-failures))
	 (if (> password-failures 7)
		(call-the-cops)
		"Incorrect password"))
	(define (call-the-cops)
	 "Calling the police...Run")
	(define (dispatch secret m)
	 (cond ((not (eq? secret password)) block-access)
		((eq? m 'withdraw) withdraw)
		((eq? m 'deposit) deposit)
		(else (error "Unknown request"))))
	dispatch))