;;(define (makejoint other-account other-password new-password)
  ;;(define (block-access amount)
    ;;"Incorrect password")
  ;;(define (dispatch secret m)
	;;(if (not (eq? secret new-password))
   ;;block-access
  ;;(cond ((eq? m 'withdraw)
	;;(other-account other-password 'withdraw))
    ;;((eq? m 'deposit)
	  ;;(other-account other-password 'deposit))
    ;;(else (error "Unknown request")))))
  ;;(if (equal? ((other-account other-password 'withdraw) 0)
;;	"Incorrect password")
	;;(begin (printf "Wrong password for existing account\n")
		;;"account doesn't exist")
	;;dispatch))
	
(define (make-joint other-account other-password new-password)
  (define (block-access amount)
    "Incorrect password") 
  (define (dispatch secret m)
    (if (not (eq? secret new-password))
	block-access
	(cond ((eq? m 'withdraw) 
	       (other-account other-password 'withdraw))
	      ((eq? m 'deposit) 
	       (other-account other-password 'deposit))
	      (else (error "Unknown request - MAKE-ACCOUNT"
			   m)))))
  (if (equal? ((other-account other-password 'withdraw) 0)
	      "Incorrect password")
      (begin (display "Wrong password for existing account\n")
	     "Account doesn't exist")
      dispatch))