(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
	  (begin (set! balance (- balance amount))
	    balance)
	  "Insufficient funds"))
  (define (deposit amount)
	(set! balance (+ balance amount))
	 balance)
  (define (block-access amount)
	"Incorrect password")
  (define (dispatch secret m)
	(if (not (eq? secret password))
	  block-access
	  (cond ((eq? m 'withdraw) withdraw)
	    ((eq? m 'deposit) deposit)
		(else (error "unknown request")))))
    dispatch)
	