(define (add-poly p1 p2)
	(if (same-variable? (variable p1) (variable p2))
		(make-poly (variable p1)
			(add-terms (term-list p1)
						(term-list p2)))
		(error "Polys not in same var")))
		
(define (mul-poly p1 p2)
	(if (same-variable? (variable p1) (variable p2))
		(make-poly (variable p1)
				(mul-terms (term-list p1)
						(term-list p2)))
		(error "poly not in save")))
		
(define (install-polynomial-package)
	(define (make-poly variable term-list)
		(cons variable term-list))
	(define (variable p) (car p))
	(define (term-list p) (cdr p))
	(define (tag p) (attach-tag 'polynomial p))
	(put 'add '(polynomial polynomial)
		(lambda (p1 p2) (tag (add-poly p1 p2))))
	(put 'mul '(polynomial polynomial)
		(lambda (p1 p2) (tag (mul-poly p1 p2))))
	(put 'make 'polynomial
		(lambda (var terms) (tag (make-poly var terms))))
			'done)